/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FeedsCreateContentFeedResponse
 */
export interface FeedsCreateContentFeedResponse {
    /**
     * A unique ID, returned from the Bulk Upload API, used for tracking the feed file.
     * @type {string}
     * @memberof FeedsCreateContentFeedResponse
     */
    'feedId'?: string;
}

