/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FeedRecordResponseErrorsInnerCausesInner
 */
export interface FeedRecordResponseErrorsInnerCausesInner {
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInnerCausesInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInnerCausesInner
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInnerCausesInner
     */
    'field'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInnerCausesInner
     */
    'type'?: string;
}

