/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedRecordResponseErrorsInnerCausesInner } from './feed-record-response-errors-inner-causes-inner';

/**
 * 
 * @export
 * @interface FeedRecordResponseErrorsInner
 */
export interface FeedRecordResponseErrorsInner {
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'info'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'field'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'severity'?: FeedRecordResponseErrorsInnerSeverityEnum;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'category'?: FeedRecordResponseErrorsInnerCategoryEnum;
    /**
     * 
     * @type {Array<FeedRecordResponseErrorsInnerCausesInner>}
     * @memberof FeedRecordResponseErrorsInner
     */
    'causes'?: Array<FeedRecordResponseErrorsInnerCausesInner>;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof FeedRecordResponseErrorsInner
     */
    'errorIdentifiers'?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'component'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'serviceName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FeedRecordResponseErrorsInner
     */
    'gatewayErrorCategory'?: FeedRecordResponseErrorsInnerGatewayErrorCategoryEnum;
}

type FeedRecordResponseErrorsInnerSeverityEnum = 'INFO' | 'WARN' | 'ERROR'
type FeedRecordResponseErrorsInnerCategoryEnum = 'APPLICATION' | 'SYSTEM' | 'REQUEST' | 'DATA'
type FeedRecordResponseErrorsInnerGatewayErrorCategoryEnum = 'INTERNAL_DATA_ERROR' | 'EXTERNAL_DATA_ERROR' | 'SYSTEM_ERROR'


