/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Information about the individual feed
 * @export
 * @interface FeedRecord
 */
export interface FeedRecord {
    /**
     * A unique ID used for tracking the Feed File
     * @type {string}
     * @memberof FeedRecord
     */
    'feedId'?: string;
    /**
     * The source of the feed
     * @type {string}
     * @memberof FeedRecord
     */
    'feedSource'?: string;
    /**
     * The feed type
     * @type {string}
     * @memberof FeedRecord
     */
    'feedType'?: string;
    /**
     * The seller ID
     * @type {string}
     * @memberof FeedRecord
     */
    'partnerId'?: string;
    /**
     * The number of items received
     * @type {number}
     * @memberof FeedRecord
     */
    'itemsReceived'?: number;
    /**
     * The number of items in the feed that have successfully processed
     * @type {number}
     * @memberof FeedRecord
     */
    'itemsSucceeded'?: number;
    /**
     * The number of items in the feed that failed due to a data or system error
     * @type {number}
     * @memberof FeedRecord
     */
    'itemsFailed'?: number;
    /**
     * The number of items in the feed that are still in progress
     * @type {number}
     * @memberof FeedRecord
     */
    'itemsProcessing'?: number;
    /**
     * Can be one of the following: RECEIVED, INPROGRESS, PROCESSED, or ERROR. For details, see the definitions listed under \'Feed Statuses\' at the beginning of this section.
     * @type {string}
     * @memberof FeedRecord
     */
    'feedStatus'?: string;
    /**
     * The date and time the feed was submitted. Format: yyyymmddThh:mm:ss.xxxz
     * @type {string}
     * @memberof FeedRecord
     */
    'feedDate'?: string;
    /**
     * The batch ID for the feed, if provided
     * @type {string}
     * @memberof FeedRecord
     */
    'batchId'?: string;
    /**
     * The most recent time the feed was modified. Format: yyyymmddThh:mm:ss.xxxz
     * @type {string}
     * @memberof FeedRecord
     */
    'modifiedDtm'?: string;
}

