/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedRecordResponseErrorsInner } from './feed-record-response-errors-inner';
import { ItemDetailsItemIngestionStatusInnerIngestionErrors } from './item-details-item-ingestion-status-inner-ingestion-errors';
import { PartnerFeedResponseItemDetails } from './partner-feed-response-item-details';

/**
 * 
 * @export
 * @interface FeedsGetFeedStatusResponse
 */
export interface FeedsGetFeedStatusResponse {
    /**
     * 
     * @type {Array<FeedRecordResponseErrorsInner>}
     * @memberof FeedsGetFeedStatusResponse
     */
    'errors'?: Array<FeedRecordResponseErrorsInner>;
    /**
     * A unique ID used for tracking the Feed File
     * @type {string}
     * @memberof FeedsGetFeedStatusResponse
     */
    'feedId'?: string;
    /**
     * Can be one of the following: RECEIVED, INPROGRESS, PROCESSED, or ERROR
     * @type {string}
     * @memberof FeedsGetFeedStatusResponse
     */
    'feedStatus'?: FeedsGetFeedStatusResponseFeedStatusEnum;
    /**
     * 
     * @type {ItemDetailsItemIngestionStatusInnerIngestionErrors}
     * @memberof FeedsGetFeedStatusResponse
     */
    'ingestionErrors'?: ItemDetailsItemIngestionStatusInnerIngestionErrors;
    /**
     * The number of items received in the feed
     * @type {number}
     * @memberof FeedsGetFeedStatusResponse
     */
    'itemsReceived'?: number;
    /**
     * The number of items in the feed that processed successfully
     * @type {number}
     * @memberof FeedsGetFeedStatusResponse
     */
    'itemsSucceeded'?: number;
    /**
     * The number of items in the feed that failed due to a data or system error
     * @type {number}
     * @memberof FeedsGetFeedStatusResponse
     */
    'itemsFailed'?: number;
    /**
     * The number of items in the feed that are still processing
     * @type {number}
     * @memberof FeedsGetFeedStatusResponse
     */
    'itemsProcessing'?: number;
    /**
     * The object response to the starting number, where 0 is the first entity available for request
     * @type {number}
     * @memberof FeedsGetFeedStatusResponse
     */
    'offset'?: number;
    /**
     * The number of items returned. Cannot be greater than 1000.
     * @type {number}
     * @memberof FeedsGetFeedStatusResponse
     */
    'limit'?: number;
    /**
     * 
     * @type {PartnerFeedResponseItemDetails}
     * @memberof FeedsGetFeedStatusResponse
     */
    'itemDetails'?: PartnerFeedResponseItemDetails;
}

type FeedsGetFeedStatusResponseFeedStatusEnum = 'RECEIVED' | 'INPROGRESS' | 'PROCESSED' | 'ERROR'


