/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedRecordResponseErrorsInnerCausesInner } from './feed-record-response-errors-inner-causes-inner';

/**
 * 
 * @export
 * @interface GatewayError
 */
export interface GatewayError {
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'info'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'field'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'severity'?: GatewayErrorSeverityEnum;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'category'?: GatewayErrorCategoryEnum;
    /**
     * 
     * @type {Array<FeedRecordResponseErrorsInnerCausesInner>}
     * @memberof GatewayError
     */
    'causes'?: Array<FeedRecordResponseErrorsInnerCausesInner>;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof GatewayError
     */
    'errorIdentifiers'?: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'component'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'serviceName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GatewayError
     */
    'gatewayErrorCategory'?: GatewayErrorGatewayErrorCategoryEnum;
}

type GatewayErrorSeverityEnum = 'INFO' | 'WARN' | 'ERROR'
type GatewayErrorCategoryEnum = 'APPLICATION' | 'SYSTEM' | 'REQUEST' | 'DATA'
type GatewayErrorGatewayErrorCategoryEnum = 'INTERNAL_DATA_ERROR' | 'EXTERNAL_DATA_ERROR' | 'SYSTEM_ERROR'


