/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IngestionErrorsIngestionErrorInner
 */
export interface IngestionErrorsIngestionErrorInner {
    /**
     * Error description
     * @type {string}
     * @memberof IngestionErrorsIngestionErrorInner
     */
    'description'?: string;
    /**
     * Error Type
     * @type {string}
     * @memberof IngestionErrorsIngestionErrorInner
     */
    'type': IngestionErrorsIngestionErrorInnerTypeEnum;
    /**
     * Error code
     * @type {string}
     * @memberof IngestionErrorsIngestionErrorInner
     */
    'code': string;
}

type IngestionErrorsIngestionErrorInnerTypeEnum = 'DATA_ERROR' | 'SYSTEM_ERROR' | 'TIMEOUT_ERROR'


