/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface IngestionError
 */
export interface IngestionError {
    /**
     * Error description
     * @type {string}
     * @memberof IngestionError
     */
    'description'?: string;
    /**
     * Error Type
     * @type {string}
     * @memberof IngestionError
     */
    'type': IngestionErrorTypeEnum;
    /**
     * Error code
     * @type {string}
     * @memberof IngestionError
     */
    'code': string;
}

type IngestionErrorTypeEnum = 'DATA_ERROR' | 'SYSTEM_ERROR' | 'TIMEOUT_ERROR'


