/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ItemDetailsItemIngestionStatusInner } from './item-details-item-ingestion-status-inner';

/**
 * List of ingestion status details for items in the feed
 * @export
 * @interface PartnerFeedResponseItemDetails
 */
export interface PartnerFeedResponseItemDetails {
    /**
     * The ingestion status of an individual item
     * @type {Array<ItemDetailsItemIngestionStatusInner>}
     * @memberof PartnerFeedResponseItemDetails
     */
    'itemIngestionStatus'?: Array<ItemDetailsItemIngestionStatusInner>;
}

