/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FeedRecordResponseErrorsInner } from './feed-record-response-errors-inner';
import { ItemDetailsItemIngestionStatusInnerIngestionErrors } from './item-details-item-ingestion-status-inner-ingestion-errors';
import { PartnerFeedResponseItemDetails } from './partner-feed-response-item-details';

/**
 * 
 * @export
 * @interface PartnerFeedResponse
 */
export interface PartnerFeedResponse {
    /**
     * 
     * @type {Array<FeedRecordResponseErrorsInner>}
     * @memberof PartnerFeedResponse
     */
    'errors'?: Array<FeedRecordResponseErrorsInner>;
    /**
     * A unique ID used for tracking the Feed File
     * @type {string}
     * @memberof PartnerFeedResponse
     */
    'feedId'?: string;
    /**
     * Can be one of the following: RECEIVED, INPROGRESS, PROCESSED, or ERROR
     * @type {string}
     * @memberof PartnerFeedResponse
     */
    'feedStatus'?: PartnerFeedResponseFeedStatusEnum;
    /**
     * 
     * @type {ItemDetailsItemIngestionStatusInnerIngestionErrors}
     * @memberof PartnerFeedResponse
     */
    'ingestionErrors'?: ItemDetailsItemIngestionStatusInnerIngestionErrors;
    /**
     * The number of items received in the feed
     * @type {number}
     * @memberof PartnerFeedResponse
     */
    'itemsReceived'?: number;
    /**
     * The number of items in the feed that processed successfully
     * @type {number}
     * @memberof PartnerFeedResponse
     */
    'itemsSucceeded'?: number;
    /**
     * The number of items in the feed that failed due to a data or system error
     * @type {number}
     * @memberof PartnerFeedResponse
     */
    'itemsFailed'?: number;
    /**
     * The number of items in the feed that are still processing
     * @type {number}
     * @memberof PartnerFeedResponse
     */
    'itemsProcessing'?: number;
    /**
     * The object response to the starting number, where 0 is the first entity available for request
     * @type {number}
     * @memberof PartnerFeedResponse
     */
    'offset'?: number;
    /**
     * The number of items returned. Cannot be greater than 1000.
     * @type {number}
     * @memberof PartnerFeedResponse
     */
    'limit'?: number;
    /**
     * 
     * @type {PartnerFeedResponseItemDetails}
     * @memberof PartnerFeedResponse
     */
    'itemDetails'?: PartnerFeedResponseItemDetails;
}

type PartnerFeedResponseFeedStatusEnum = 'RECEIVED' | 'INPROGRESS' | 'PROCESSED' | 'ERROR'


