/*
Content Management

The content management feed allows you to process content for items in bulk. You can take in content via the content feeds. Use the XSDs to manage content.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ItemDetailsItemIngestionStatusInnerIngestionErrors } from './item-details-item-ingestion-status-inner-ingestion-errors';

/**
 * The ingestion status of an individual item
 * @export
 * @interface PartnerItemIngestionStatus
 */
export interface PartnerItemIngestionStatus {
    /**
     * Mart ID that a user or seller uses for a marketplace
     * @type {number}
     * @memberof PartnerItemIngestionStatus
     */
    'martId'?: number;
    /**
     * An arbitrary alphanumeric unique ID, seller-specified, identifying each item.
     * @type {string}
     * @memberof PartnerItemIngestionStatus
     */
    'sku'?: string;
    /**
     * An alphanumeric product ID, generated by Walmart
     * @type {string}
     * @memberof PartnerItemIngestionStatus
     */
    'wpid'?: string;
    /**
     * index of items in the feed
     * @type {number}
     * @memberof PartnerItemIngestionStatus
     */
    'index'?: number;
    /**
     * Can be one of the following: DATA_ERROR, SYSTEM_ERROR, TIMEOUT_ERROR, or INPROGRESS
     * @type {string}
     * @memberof PartnerItemIngestionStatus
     */
    'ingestionStatus': PartnerItemIngestionStatusIngestionStatusEnum;
    /**
     * 
     * @type {ItemDetailsItemIngestionStatusInnerIngestionErrors}
     * @memberof PartnerItemIngestionStatus
     */
    'ingestionErrors'?: ItemDetailsItemIngestionStatusInnerIngestionErrors;
}

type PartnerItemIngestionStatusIngestionStatusEnum = 'INPROGRESS' | 'SUCCESS' | 'DATA_ERROR' | 'SYSTEM_ERROR' | 'TIMEOUT_ERROR'


